###############################################################################
# Use this file to overwrite the main config file.
###############################################################################

system
  cache: 'APC'