parameters:
    logger.class: "\Webiny\Component\Logger\Logger"
    logger.driver.class: "\Webiny\Component\Logger\Drivers\Webiny"

services:
    logger:
        handlers:
            UDPTray:
                class: "\Webiny\Component\Logger\Handlers\UDPHandler"
                arguments: [[], true, true, null]
                calls:
                    - [setFormatter, ["@logger.formatters.Tray"]]
                scope: container # Singleton - default
        formatters:
            Tray:
                class: "\Webiny\Component\Logger\Formatters\WebinyTrayFormatter"
        processors:
        EventManager:
            class: "%logger.class%"
            arguments: ["EventManager", "%logger.driver.class%"]
            calls:
              - [addHandler, ["@logger.handlers.UDPTray"]]
            scope: container #Singleton - default

        MyLogger:
            class: "%logger.class%"
            arguments:
                name: "ECommerce"
                driver:
                    object: "%logger.driver.class%"
                        ili
                    object: "@logger.drivers.Webiny"
                    object_arguments: ["ECommerce.ShoppingCart"]
            calls:
              - [addHandler, ["@logger.handlers.UDPTray"]]
            scope: container #Singleton - default